//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntersectionStatistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int id_stat { get; set; }
        public Nullable<int> id_lap { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> decibels { get; set; }
        public Nullable<double> gas { get; set; }
        public Nullable<int> counter { get; set; }
    }
}
